application: shallowcoffee
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
    
- url: /
  script: main.py

- url: /loc.*
  script: main.py
  
- url: /latest.*
  script: main.py

- url: /home.*
  script: home.py
  
- url: /updateModels.*
  script: main.py

- url: /upload_pic.*
  script: upload_pic.py

- url: /new_profile.*
  script: new_profile.py

- url: /new_venue.*
  script: venue.py

- url: /venue.*
  script: venue.py

- url: /image.*
  script: servImage.py
  
- url: /fullimg.*
  script: fullimg.py
  
- url: /thumb.*
  script: servthumb.py
  
- url: /test/.*
  script: main.py
  
- url: /profile.*
  script: profile.py

- url: /invite.*
  script: invite.py
  
- url: /rpc.*
  script: rpc.py
